First_Name = input("First Name? ")
Surname = input("Surname? ")
Age = input("Age? ")
New_Patient = input("New Patient? ")
print("Name: ", First_Name, "Surname: ", Surname, "Age", Age, "New Patient: ", New_Patient)
